# -*- coding: utf-8 -*-
"""logic 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KYcB6tP5CFBbDI4z08DCbjlaErVJWFyQ
"""

def crange(a,b):
    return range(a, b + 1)

def printnln(a):
      print(a, end="")

for y in crange(1,9):
  for x in crange(1,9):
    # Conditions for the hourglass pattern
    # Top half (including middle row): x between y and 10-y
    # Bottom half (excluding middle row): x between 10-y and y
    if (y <= 5 and x >= y and x <= 10 - y) or \
       (y > 5 and x >= 10 - y and x <= y):
      printnln("*")
    else:
      printnln("-")
  print()

"""##### Copyright 2025 Google LLC."""

for y in range(1,10):
  for x in range(1,10):
    if y == x:
      print("kecoak", end="")
    else:
      print("@", end="")
  print()

for y in range(1,10):
  for x in range(1,10):
    if x == 9 - (y - 1):
      print("kocak", end="")
    else:
      print("#", end="")
  print()

# @title Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

def crange(a,b):
    return range(a, b + 1)
for a in crange(1,9):
    print(a)

"""# Gemini API: Prompting Quickstart

<a target="_blank" href="https://colab.research.google.com/github/google-gemini/cookbook/blob/main/quickstarts/Prompting.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" height=30/></a>
"""

def crange(a,b):
    return range(a, b + 1)

def printnln(a):
      print(a, end="")

printnln("ambee")
printnln("kambembee")

for y in crange(1,10-1):
  for x in crange(1,10-1):
    if y == x:
      printnln("kecoak")
    else:
      printnln("@",)
  print()

for y in crange(1,9):
  for x in crange(1,9):
    if x == 9 - (y - 1):
      printnln("kocak")
    else:
      printnln("#")
  print()

"""for y in crange(1,9):
  for x in crange(1,9):
    if y == x or x == 9 - (y - 1):
      printnln("@")
    else:
      printnln("#")
  print()

This notebook contains examples of how to write and run your first prompts with the Gemini API.

for y in crange(1,10-1):
  for x in crange(1,10-1):
    if x == y:
      printnln("@")
    elif x == 9 - (y - 1):
      printnln("@")
    else:
      printnln("#")
  print()
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install -U -q "google-genai>=1.4.0" # 1.4.0 is needed for chat history

for y in crange(1,9):
  for x in crange(1,9):
    if x >= 9 - (y - 1):
      printnln("&")
    else:
      printnln("%")
  print()

for y in crange(1,9):
  for x in crange(1,9):
    if x <= 9 - (y - 1):
      printnln("*")
    else:
      printnln("-")
  print()

for y in crange(1,9):
  for x in crange(1,9):
    if x == y:
      printnln("*")
    elif x == 9 - (y - 1):
      printnln("*")
    elif x == 5:
      printnln("*")
    elif y == 5:
      printnln("*")
    else:
      printnln("-")
  print()

"""### Set up your API key

To run the following cell, your API key must be stored it in a Colab Secret named `GOOGLE_API_KEY`. If you don't already have an API key, or you're not sure how to create a Colab Secret, see the [Authentication](https://github.com/google-gemini/cookbook/blob/main/quickstarts/Authentication.ipynb) quickstart for an example.
"""

for y in crange(1,9):
  for x in crange(1,9):
    if x <= y:
      printnln("@")
    else:
      printnln("#")
  print()

for y in crange(1,9):
  for x in crange(1,9):
    if x >= 9 - (y - 1):
      printnln("*")
    else:
      printnln("_")
  print()

from google.colab import userdata
from google import genai

GOOGLE_API_KEY = userdata.get('GOOGLE_API_KEY')
client = genai.Client(api_key=GOOGLE_API_KEY)



def crange(a,b):
    return range(a, b + 1)

def printnln(a):
      print(a, end="")

for y in crange(1,9):
  for x in crange(1,9):
    if y <= 9 // 2:
     if x >= y and x <= 9 - (y - 1):
      printnln("*")
    elif x <= y and x >= 9 - (y - 1):
      printnln("*")
  else:
      printnln("_")
  print()

def crange(a,b):
    return range(a, b + 1)

def printnln(a):
      print(a, end="")

for y in crange(1,9):
  for x in crange(1,9):
    # Conditions for the hourglass pattern
    # Top half (including middle row): x between y and 10-y
    # Bottom half (excluding middle row): x between 10-y and y
    if (y <= 5 and x >= y and x <= 10 - y) or \
       (y > 5 and x >= 10 - y and x <= y):
      printnln("*")
    else:
      printnln("_")
  print()

n = 9  # lebar jam pasir

for y in crange(1, n):        # baris
    for x in crange(1, n):    # kolom
        if y <= n // 2:
            # Bagian kiri jam pasir
            if x >= y and x <= n - y + 1:
                printnln("*")
            else:
                printnln(" ")
        else:
            # Bagian kanan jam pasir
            if x >= n - y + 1 and x <= y:
                printnln("*")
            else:
                printnln(" ")
    print()

"""for y in crange(1,9):
  for x in crange(1,9):
    if (x >=4 and y <= 5 and x<=10-4) or \
        (y > 5 and x >=10-4 and x <=4):
      printnln("*")
    else:
      printnln("_")
  print()

"""

for y in crange(1,9):
  for x in crange(1,9):

"""## Select your model

Now select the model you want to use in this guide, either by selecting one in the list or writing it down. Keep in mind that some models, like the 2.5 ones are thinking models and thus take slightly more time to respond (cf. [thinking notebook](./Get_started_thinking.ipynb) for more details and in particular learn how to switch the thiking off).
"""

MODEL_ID = "gemini-2.5-flash" # @param ["gemini-2.5-flash-lite", "gemini-2.5-flash", "gemini-2.5-pro","gemini-3-pro-preview"] {"allow-input":true, isTemplate: true}

"""## Run your first prompt

Use the `generate_content` method to generate responses to your prompts. You can pass text directly to generate_content, and use the `.text` property to get the text content of the response.
"""

from IPython.display import Markdown

response = client.models.generate_content(
    model=MODEL_ID,
    contents="Give me python code to sort a list"
)

display(Markdown(response.text))

"""## Use images in your prompt

Here you will download an image from a URL and pass that image in our prompt.

First, you download the image and load it with PIL:
"""

!curl -o image.jpg "https://storage.googleapis.com/generativeai-downloads/images/jetpack.jpg"

import PIL.Image
img = PIL.Image.open('image.jpg')
img

prompt = """
    This image contains a sketch of a potential product along with some notes.
    Given the product sketch, describe the product as thoroughly as possible based on what you
   see in the image, making sure to note all of the product features. Return output in json format:
   {description: description, features: [feature1, feature2, feature3, etc]}
"""

"""Then you can include the image in our prompt by just passing a list of items to `generate_content`."""

response = client.models.generate_content(
    model=MODEL_ID,
    contents=[prompt, img],
)

print(response.text)

"""## Have a chat

The Gemini API enables you to have freeform conversations across multiple turns.

The [ChatSession](https://ai.google.dev/api/python/google/generativeai/ChatSession) class will store the conversation history for multi-turn interactions.
"""

chat = client.chats.create(model=MODEL_ID)

response = chat.send_message(
    message="In one sentence, explain how a computer works to a young child."
)

print(response.text)

"""You can see the chat history:"""

messages = chat.get_history()
for message in messages:
  print(f"{message.role}: {message.parts[0].text}")

"""You can keep sending messages to continue the conversation:"""

response = chat.send_message("Okay, how about a more detailed explanation to a high schooler?")

print(response.text)

"""## Set the temperature

Every prompt you send to the model includes parameters that control how the model generates responses. Use a `types.GenerateContentConfig` to set these, or omit it to use the defaults.

Temperature controls the degree of randomness in token selection. Use higher values for more creative responses, and lower values for more deterministic responses.

Note: Although you can set the `candidate_count` in the generation_config, 2.0 and later models will only return a single candidate at the this time.
"""

from google.genai import types

response = client.models.generate_content(
    model=MODEL_ID,
    contents='Give me a numbered list of cat facts.',
    config=types.GenerateContentConfig(
        max_output_tokens=2000,
        temperature=1.9,
        stop_sequences=['\n6'] # Limit to 5 facts.
    )
)

display(Markdown(response.text))

"""## Learn more

There's lots more to learn!

* For more fun prompts, check out [Market a Jetpack](https://github.com/google-gemini/cookbook/blob/main/examples/Market_a_Jet_Backpack.ipynb).
* Check out the [safety quickstart](https://github.com/google-gemini/cookbook/blob/main/quickstarts/Safety.ipynb) next to learn about the Gemini API's configurable safety settings, and what to do if your prompt is blocked.
* For lots more details on using the Python SDK, check out the [get started notebook](./Get_started.ipynb) or the [documentation's quickstart](https://ai.google.dev/tutorials/python_quickstart).
"""