# -*- coding: utf-8 -*-
"""logic 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19sB2oNQsOmjFfcnO3-DQrnOlonaY16Hx
"""

# CUATOM RANGE
def crange(a,b):
    return range(a, b + 1)
def printnln(a):
    print(a, end="")

#SOAL 1
#membuat bintang menjadi angka ganjil (j) with (n * 2 - 1 jk dri 0) | (n * 2 -1 jika dr 1)
#for n in crange(1,9):
 #   j = n * 2 - 1
 #   print(j)

for y in crange(1,9):
    for x in crange(1,9):
        if x == y:
            j = x * 2 - 1
            printnln(j)
        else:
            printnln("_")
    print()

#SOAL 2

for y in crange(1,9):
    for x in crange(1,9):
        if x == 9 - (y - 1):
           n = x * 2 - 2
           printnln(n)
        else:
            printnln("_")
    print()

for y in crange(1,9):
    for x in crange(1,9):
        if x == y:
         j = x * 2 - 1
         printnln(j)
        elif x == 9 - (y - 1):
         n = x * 2 - 2
         printnln(n)
        else:
            printnln("_")

    print()

for y in crange(1,9):
    for x in crange(1,9):
        if x == y:
         n = x * 2 - 2
         printnln(n)
        elif x == 9 - (y - 1):
         j = x * 2 - 1
         printnln(j)
        else:
            printnln("_")

    print()

#SOAl 5
for y in crange(1,9):
    for x in crange(1,9):
        if x ==y  or x == 5:
            j = y * 2 - 1
            printnln(j)
        elif x == 9 - (y - 1) or y == 5:
            n = x * 2 - 2
            printnln(n)
        else:
            printnln("_")
    print()

#SOAL 6
for y in crange(1,9):
    for x in crange(1,9):
        if x <=y:
            j = x * 2 - 1
            printnln(j)
        else:
            printnln("_")
    print()

for y in crange(1,9):
    for x in crange(1,9):
        if x >= 9 - (y - 1):
            V = 9 - (y - 1)
            n = V * 2 - 2
            printnln(n)
        else:
            printnln("_")
    print()

#SOAL 7

for y in crange(1,9):
    for x in crange(1,9):
        if x == y:
            j = y * 2 - 1
            printnln(j)
        elif x == 9 - (y - 1):
            n = x * 2 - 2
            printnln(n)
        elif x > y and x < 9 - (y - 1):
            printnln("A")
        elif x < y and x > 9 - (y - 1):
            printnln("B")
        else:
            printnln("_")
    print()

for  y in crange(1,9):
    for x in crange(1,9):
        if x == y:
            j = y * 2 - 1
            printnln(j)
        elif x == 9 -  (y - 1):
            n = x * 2 - 2
            printnln(n)
        elif x < y and x < 9 - (y - 1):
            printnln("A")
        elif x > y and x > 9 - (y - 1):
            printnln("B")
        else:
            printnln("_")
    print()

